%% make_slr_plr_cases_case24.m
% Builds SLR + PLR branch ratings cases for RTS-24 using your PLR_dataset.mat
%
% Your PLR dataset:
%   - Tmax_list (e.g., 70:5:100)
%   - I_ref     (current grid in A)
%   - Pexc_mat  (size: [num_I x num_Tmax], exceedance probability in %)
%
% Key idea:
%   - Pick a reference Tmax (e.g., 75°C)
%   - Define an "SLR-equivalent" anchor current from SAME curve at small exceedance (e.g., 0.1%)
%   - For each PLR exceedance target (e.g., 2%), get I_PLR directly from curve
%   - Scale MATPOWER RATE_A (MVA) for LINES only by factor = I_PLR / I_SLR_ref

clear; clc;
define_constants;

%% ---------------- USER SETTINGS ----------------
case_name = 'case24_ieee_rts';

plr_matfile     = "PLR_dataset.mat";  % generated by run_many_Tmax.m
Tmax_ref        = 75;                 % which Tmax curve to use
ex_slr_ref_pct  = 0.1;                % anchor exceedance defining "SLR-equivalent" current
ex_targets_pct  = [1 2 5 7 10];       % PLR exceedance levels you want cases for

% Optional: only scale a subset of lines (leave empty to scale ALL lines)
branch_subset = [];  % e.g., [1 2 5 9]; otherwise keep empty

%% 1) Load RTS case
mpc0 = loadcase(case_name);

%% 2) Identify transformers vs lines
fbus = mpc0.branch(:, F_BUS);
tbus = mpc0.branch(:, T_BUS);

Vf_kV = mpc0.bus(fbus, BASE_KV);
Vt_kV = mpc0.bus(tbus, BASE_KV);

is_diff_kV = abs(Vf_kV - Vt_kV) > 1e-3;

tap = mpc0.branch(:, TAP);
is_tapped = (tap ~= 0) & (abs(tap - 1) > 1e-6);

is_xfmr = is_diff_kV | is_tapped;
is_line = ~is_xfmr;

fprintf("Detected %d lines and %d transformers.\n", sum(is_line), sum(is_xfmr));
fprintf("Transformers will keep original RATE_A.\n");

%% 3) Define which line indices to scale
line_idx = find(is_line);

if ~isempty(branch_subset)
    % user-specified subset: intersect with lines only
    scale_idx = intersect(line_idx, branch_subset(:));
    fprintf("Scaling a subset of %d lines (user-selected).\n", numel(scale_idx));
else
    % scale all lines
    scale_idx = line_idx;
    fprintf("Scaling ALL %d lines.\n", numel(scale_idx));
end

%% 4) Load PLR dataset and select the Tmax curve
S = load(plr_matfile, "Tmax_list", "I_ref", "Pexc_mat");

Tmax_list = S.Tmax_list(:);
I_ref     = S.I_ref(:);
Pexc_mat  = S.Pexc_mat;

idxT = find(Tmax_list == Tmax_ref, 1);
if isempty(idxT)
    error("Tmax=%g not found in %s. Available Tmax: %s", ...
        Tmax_ref, plr_matfile, strjoin(string(Tmax_list), ", "));
end

Pexc_I = Pexc_mat(:, idxT);   % exceedance curve (%) vs current for chosen Tmax

%% 5) Compute SLR anchor current from curve
I_SLR_ref_A = rating_from_exceedance(I_ref, Pexc_I, ex_slr_ref_pct);

if isnan(I_SLR_ref_A)
    error("SLR anchor returned NaN. ex_slr_ref_pct=%.3f%% may be outside curve range.", ex_slr_ref_pct);
end

fprintf("\nUsing Tmax=%d°C curve.\n", Tmax_ref);
fprintf("SLR anchor: exceedance %.3f%% -> I_SLR_ref = %.2f A\n", ex_slr_ref_pct, I_SLR_ref_A);

%% 6) Compute PLR currents from curve (this is where your 2%% -> 1105.5A comes from)
I_plr_A = nan(size(ex_targets_pct));
fac     = nan(size(ex_targets_pct));

for k = 1:numel(ex_targets_pct)
    exk = ex_targets_pct(k);
    I_plr_A(k) = rating_from_exceedance(I_ref, Pexc_I, exk);

    if isnan(I_plr_A(k))
        error("PLR current returned NaN for exceedance %.3f%%. Curve range may be too short.", exk);
    end

    fac(k) = I_plr_A(k) / I_SLR_ref_A;

    fprintf("PLR %.3f%% -> I_PLR = %.2f A | factor (I_PLR/I_SLR) = %.4f\n", ...
        exk, I_plr_A(k), fac(k));
end

%% 7) Build SLR case (baseline ratings)
% Here we treat the ORIGINAL RTS case as the SLR baseline in MVA.
% We do NOT overwrite RATE_A with an absolute ampacity unless you explicitly want that.
mpc_slr = mpc0;

%% 8) Build PLR cases by scaling RATE_A for lines only
nC = numel(ex_targets_pct);
mpc_plr = cell(nC,1);
names   = strings(nC,1);

for k = 1:nC
    exk = ex_targets_pct(k);
    names(k) = "PLR_" + strrep(string(exk), ".", "p") + "pct";

    mpc_plr{k} = mpc_slr;
    mpc_plr{k}.branch(scale_idx, RATE_A) = mpc_slr.branch(scale_idx, RATE_A) * fac(k);

    % transformers unchanged because they are not in scale_idx (scale_idx contains lines only)
end

%% 9) Sanity check: show a few scaled lines for PLR 2% if present
idx2 = find(ex_targets_pct == 2, 1);
if ~isempty(idx2)
    kshow = scale_idx(1:min(5,numel(scale_idx)));
    disp("Example scaled LINE branches (SLR vs PLR 2% RATE_A):");
    disp(table(kshow, Vf_kV(kshow), ...
        mpc_slr.branch(kshow, RATE_A), ...
        mpc_plr{idx2}.branch(kshow, RATE_A), ...
        'VariableNames', {'branch_id','kV','RATEA_SLR','RATEA_PLR2'}));
end

%% 10) Save for your EENS simulation scripts
save("SLR_PLR_cases_case24.mat", ...
    "mpc0", "mpc_slr", "mpc_plr", "names", ...
    "is_line", "is_xfmr", "scale_idx", ...
    "Tmax_ref", "ex_slr_ref_pct", "ex_targets_pct", ...
    "I_SLR_ref_A", "I_plr_A", "fac");

disp("Saved: SLR_PLR_cases_case24.mat");